# Generated by Django 5.2.4 on 2026-01-18 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0009_alter_cliente_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Plano')),
                ('tipo', models.CharField(choices=[('ESSENCIAL', 'Essencial'), ('PROFISSIONAL', 'Profissional'), ('AVANCADO', 'Avançado'), ('ENTERPRISE', 'Enterprise')], max_length=20, unique=True, verbose_name='Tipo de Plano')),
                ('descricao', models.TextField(blank=True, default='', verbose_name='Descrição')),
                ('valor_mensal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Mensal (R$)')),
                ('limite_usuarios', models.IntegerField(default=5, help_text='Número máximo de usuários. 0 = ilimitado')),
                ('limite_equipamentos', models.IntegerField(default=0, help_text='Número máximo de equipamentos. 0 = ilimitado')),
                ('limite_empreendimentos', models.IntegerField(default=0, help_text='Número máximo de empreendimentos. 0 = ilimitado')),
                ('modulos_habilitados', models.JSONField(default=list, help_text='Lista de módulos disponíveis neste plano')),
                ('bot_telegram', models.BooleanField(default=False, verbose_name='Bot Telegram')),
                ('qr_code_equipamento', models.BooleanField(default=False, verbose_name='QR Code por Equipamento')),
                ('checklist_mobile', models.BooleanField(default=False, verbose_name='Checklist Mobile')),
                ('backups_automaticos', models.BooleanField(default=False, verbose_name='Backups Automáticos')),
                ('suporte_prioritario', models.BooleanField(default=False, verbose_name='Suporte Prioritário')),
                ('suporte_whatsapp', models.BooleanField(default=False, verbose_name='Suporte WhatsApp')),
                ('multiempresa', models.BooleanField(default=False, verbose_name='Multi-empresa')),
                ('customizacoes', models.BooleanField(default=False, verbose_name='Customizações')),
                ('hospedagem_dedicada', models.BooleanField(default=False, verbose_name='Hospedagem Dedicada')),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.IntegerField(default=0, help_text='Ordem de exibição')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
                'ordering': ['ordem', 'valor_mensal'],
            },
        ),
        migrations.CreateModel(
            name='AssinaturaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ATIVA', 'Ativa'), ('SUSPENSA', 'Suspensa'), ('CANCELADA', 'Cancelada'), ('TRIAL', 'Trial')], default='ATIVA', max_length=20)),
                ('data_inicio', models.DateField(auto_now_add=True)),
                ('data_fim_trial', models.DateField(blank=True, help_text='Data de término do período trial', null=True)),
                ('data_proximo_pagamento', models.DateField(blank=True, null=True)),
                ('data_cancelamento', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assinatura', to='cadastro.cliente')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assinaturas', to='cadastro.plano')),
            ],
            options={
                'verbose_name': 'Assinatura',
                'verbose_name_plural': 'Assinaturas',
            },
        ),
    ]
