# Generated by Django 5.2.8 on 2026-02-16 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0010_plano_assinaturacliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='empreendimento',
            name='endereco_geocodificado',
            field=models.CharField(blank=True, default='', help_text='Endereço obtido via geocodificação reversa', max_length=300),
        ),
        migrations.AddField(
            model_name='empreendimento',
            name='raio_geofence',
            field=models.PositiveIntegerField(default=500, help_text='Raio em metros para validação de geofence (área válida para checklists)'),
        ),
        migrations.AlterField(
            model_name='empreendimento',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Latitude do empreendimento', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='empreendimento',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Longitude do empreendimento', max_digits=11, null=True),
        ),
    ]
