# Generated by Django 5.2.8 on 2026-02-17 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0011_add_geofence_empreendimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empreendimento',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Latitude do empreendimento', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='empreendimento',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Longitude do empreendimento', max_digits=12, null=True),
        ),
    ]
