# Generated by Django 5.2.8 on 2026-02-28 20:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0012_fix_gps_precision'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='preco_por_equipamento',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor cobrado por equipamento ativo por mês', max_digits=8, verbose_name='Preço por Equipamento (R$/mês)'),
        ),
    ]
