# Generated by Django 5.2.6 on 2025-10-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='documento',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20),
        ),
    ]
