# Generated by Django 5.2.5 on 2025-10-29 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_add_uuid_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/clientes/', verbose_name='QR Code'),
        ),
        migrations.AddField(
            model_name='empreendimento',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/empreendimentos/', verbose_name='QR Code'),
        ),
    ]
