# Generated by Django 5.2.4 on 2025-12-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0006_cliente_qr_code_empreendimento_qr_code'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.UniqueConstraint(condition=models.Q(('documento', ''), _negated=True), fields=('tipo_pessoa', 'documento'), name='unique_cliente_documento'),
        ),
    ]
