# Generated by Django 5.2.4 on 2026-01-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens_servico', '0002_alter_ordemservico_tecnico_responsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='horimetro_final',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Horímetro/KM ao finalizar o serviço', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='horimetro_inicial',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Horímetro/KM no início do serviço', max_digits=12, null=True),
        ),
    ]
