# Generated by Django 5.2.4 on 2025-11-01 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_supervisor_endereco_fields'),
        ('equipamentos', '0003_equipamento_qr_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abastecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('horimetro_km', models.DecimalField(decimal_places=2, help_text='Horímetro ou KM no momento do abastecimento', max_digits=12)),
                ('tipo_combustivel', models.CharField(choices=[('DIESEL', 'Diesel'), ('GASOLINA', 'Gasolina'), ('ETANOL', 'Etanol'), ('GNV', 'GNV'), ('OUTRO', 'Outro')], default='DIESEL', max_length=20)),
                ('quantidade_litros', models.DecimalField(decimal_places=2, help_text='Quantidade em litros', max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, help_text='Valor total do abastecimento', max_digits=10)),
                ('valor_unitario', models.DecimalField(blank=True, decimal_places=3, help_text='Valor por litro (calculado automaticamente)', max_digits=10, null=True)),
                ('local', models.CharField(blank=True, default='', max_length=150)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('numero_nota', models.CharField(blank=True, default='', max_length=50)),
                ('nota_fiscal', models.FileField(blank=True, null=True, upload_to='abastecimentos/notas/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abastecimentos', to='equipamentos.equipamento')),
                ('operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abastecimentos', to='core.operador')),
            ],
            options={
                'ordering': ['-data', '-horimetro_km'],
                'indexes': [models.Index(fields=['equipamento', '-data'], name='abastecimen_equipam_02e9d9_idx'), models.Index(fields=['data'], name='abastecimen_data_7635c7_idx')],
            },
        ),
    ]
