# Generated by Django 5.2.5 on 2025-11-01 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abastecimentos', '0001_initial'),
        ('almoxarifado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abastecimento',
            name='local_estoque',
            field=models.ForeignKey(blank=True, help_text='Local de onde saiu o combustível', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='abastecimentos', to='almoxarifado.localestoque'),
        ),
        migrations.AddField(
            model_name='abastecimento',
            name='produto',
            field=models.ForeignKey(blank=True, help_text='Produto de combustível do almoxarifado', limit_choices_to={'tipo': 'COMBUSTIVEL'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='abastecimentos', to='almoxarifado.produto'),
        ),
        migrations.AlterField(
            model_name='abastecimento',
            name='local',
            field=models.CharField(blank=True, default='', help_text='Descrição do local (alternativa)', max_length=150),
        ),
    ]
