# Generated by Django 5.2.8 on 2026-02-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abastecimentos', '0002_abastecimento_local_estoque_abastecimento_produto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abastecimento',
            name='origem',
            field=models.CharField(choices=[('ALMOXARIFADO', 'Almoxarifado'), ('POSTO', 'Posto de Gasolina')], default='POSTO', help_text='Origem do combustível: Almoxarifado ou Posto de Gasolina', max_length=20),
        ),
    ]
