# Generated by Django 5.2.8 on 2026-02-04 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0004_historicalequipamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaoequipamento',
            name='origem',
            field=models.CharField(choices=[('CHECKLIST', 'Checklist'), ('ABASTECIMENTO', 'Abastecimento'), ('MANUTENCAO', 'Manutenção'), ('MANUTENCAO_PREVENTIVA', 'Manutenção Preventiva'), ('MANUAL', 'Manual')], default='MANUAL', max_length=30),
        ),
    ]
