# Generated by Django 5.2.8 on 2026-02-24 10:56

from django.db import migrations, models


def add_field_if_not_exists(apps, schema_editor):
    """
    Adiciona campos apenas se não existirem.
    Necessário porque a migration 0015 foi aplicada em produção antes de ser removida.
    """
    from django.db import connection

    with connection.cursor() as cursor:
        # Verifica quais colunas já existem
        cursor.execute("""
            SELECT column_name
            FROM information_schema.columns
            WHERE table_name='equipamentos_equipamento'
        """)
        existing_columns = {row[0] for row in cursor.fetchall()}

        # Lista de campos a adicionar
        fields_to_add = [
            ('data_ultima_leitura', 'TIMESTAMP', 'NULL'),
            ('status_operacional', "VARCHAR(20) DEFAULT 'OPERACIONAL'", 'NOT NULL'),
            ('data_ultima_manutencao', 'DATE', 'NULL'),
            ('leitura_ultima_manutencao', 'NUMERIC(12, 2)', 'NULL'),
            ('proxima_manutencao_leitura', 'NUMERIC(12, 2)', 'NULL'),
            ('proxima_manutencao_data', 'DATE', 'NULL'),
        ]

        # Adicionar campos que não existem em equipamentos_equipamento
        for field_name, field_type, nullable in fields_to_add:
            if field_name not in existing_columns:
                cursor.execute(f"""
                    ALTER TABLE equipamentos_equipamento
                    ADD COLUMN {field_name} {field_type} {nullable}
                """)
                print(f"✓ Adicionado campo {field_name} em equipamentos_equipamento")
            else:
                print(f"→ Campo {field_name} já existe em equipamentos_equipamento")

        # Verificar histórico
        cursor.execute("""
            SELECT column_name
            FROM information_schema.columns
            WHERE table_name='equipamentos_equipamento_history'
        """)
        existing_history_columns = {row[0] for row in cursor.fetchall()}

        # Adicionar campos que não existem em equipamentos_equipamento_history
        for field_name, field_type, nullable in fields_to_add:
            if field_name not in existing_history_columns:
                cursor.execute(f"""
                    ALTER TABLE equipamentos_equipamento_history
                    ADD COLUMN {field_name} {field_type} {nullable}
                """)
                print(f"✓ Adicionado campo {field_name} em equipamentos_equipamento_history")
            else:
                print(f"→ Campo {field_name} já existe em equipamentos_equipamento_history")


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0007_historicalequipamento_consumo_nominal_l_h_and_more'),
    ]

    operations = [
        migrations.RunPython(add_field_if_not_exists, migrations.RunPython.noop),
    ]
