# Generated by Django 5.2.8 on 2026-02-03 20:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('almoxarifado', '0001_initial'),
        ('cadastro', '0010_plano_assinaturacliente'),
        ('equipamentos', '0004_historicalequipamento'),
        ('orcamentos', '0002_orcamento_km_deslocado_orcamento_valor_km_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome / Razão Social')),
                ('cnpj_cpf', models.CharField(blank=True, default='', max_length=20, verbose_name='CNPJ/CPF')),
                ('contato', models.CharField(blank=True, default='', max_length=150, verbose_name='Pessoa de Contato')),
                ('telefone', models.CharField(blank=True, default='', max_length=30, verbose_name='Telefone')),
                ('whatsapp', models.CharField(blank=True, default='', max_length=30, verbose_name='WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('especialidade', models.CharField(blank=True, default='', help_text='Ex: Peças Hidráulicas, Filtros, Material Elétrico', max_length=200, verbose_name='Especialidade')),
                ('logradouro', models.CharField(blank=True, default='', max_length=255)),
                ('numero', models.CharField(blank=True, default='', max_length=20)),
                ('complemento', models.CharField(blank=True, default='', max_length=100)),
                ('bairro', models.CharField(blank=True, default='', max_length=100)),
                ('cidade', models.CharField(blank=True, default='', max_length=100)),
                ('uf', models.CharField(blank=True, default='', max_length=2)),
                ('cep', models.CharField(blank=True, default='', max_length=9)),
                ('observacoes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='PedidoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Número')),
                ('destino', models.CharField(choices=[('PROPRIO', 'Compra Própria (Almoxarifado)'), ('CLIENTE', 'Encaminhar para Cliente')], default='PROPRIO', max_length=10, verbose_name='Destino Financeiro')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('ENVIADO', 'Enviado ao Fornecedor'), ('APROVADO', 'Aprovado'), ('PARCIAL', 'Entregue Parcialmente'), ('ENTREGUE', 'Entregue'), ('CANCELADO', 'Cancelado')], default='RASCUNHO', max_length=10, verbose_name='Status')),
                ('data_pedido', models.DateField(auto_now_add=True, verbose_name='Data do Pedido')),
                ('data_previsao', models.DateField(blank=True, null=True, verbose_name='Previsão de Entrega')),
                ('data_entrega', models.DateField(blank=True, null=True, verbose_name='Data de Entrega Efetiva')),
                ('numero_nf', models.CharField(blank=True, default='', max_length=60, verbose_name='Número da NF')),
                ('nota_fiscal', models.FileField(blank=True, null=True, upload_to='compras/nf/%Y/%m/', verbose_name='Nota Fiscal (PDF/Foto)')),
                ('observacoes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Valor Total')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_compra', to='cadastro.cliente', verbose_name='Cliente')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_compra_criados', to=settings.AUTH_USER_MODEL)),
                ('equipamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_compra', to='equipamentos.equipamento', verbose_name='Equipamento')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='compras.fornecedor', verbose_name='Fornecedor')),
                ('local_estoque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_compra', to='almoxarifado.localestoque', verbose_name='Local de Estoque')),
                ('orcamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_compra', to='orcamentos.orcamento', verbose_name='Orçamento Vinculado')),
            ],
            options={
                'verbose_name': 'Pedido de Compra',
                'verbose_name_plural': 'Pedidos de Compra',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedidoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=300, verbose_name='Descrição')),
                ('codigo_fornecedor', models.CharField(blank=True, default='', max_length=100, verbose_name='Código no Fornecedor')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='Quantidade')),
                ('unidade', models.CharField(default='UN', max_length=20, verbose_name='Unidade')),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor Unitário')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Valor Total')),
                ('quantidade_recebida', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Qtd Recebida')),
                ('entregue', models.BooleanField(default=False, verbose_name='Entregue')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_compra', to='almoxarifado.produto', verbose_name='Produto do Almoxarifado')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='compras.pedidocompra', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Item do Pedido',
                'verbose_name_plural': 'Itens do Pedido',
                'ordering': ['id'],
            },
        ),
    ]
