# Generated by Django 5.2.8 on 2026-02-03 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
        ('ordens_servico', '0003_ordemservico_horimetro_final_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidocompra',
            name='ordem_servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_compra', to='ordens_servico.ordemservico', verbose_name='Ordem de Servico'),
        ),
    ]
