# Generated by Django 5.2.8 on 2026-02-14 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_add_ordem_servico_to_pedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Local')),
                ('responsavel', models.CharField(blank=True, default='', max_length=150, verbose_name='Responsável')),
                ('telefone', models.CharField(blank=True, default='', max_length=30, verbose_name='Telefone')),
                ('logradouro', models.CharField(blank=True, default='', max_length=255, verbose_name='Logradouro')),
                ('numero', models.CharField(blank=True, default='', max_length=20, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, default='', max_length=100, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, default='', max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, default='', max_length=100, verbose_name='Cidade')),
                ('uf', models.CharField(blank=True, default='', max_length=2, verbose_name='UF')),
                ('cep', models.CharField(blank=True, default='', max_length=9, verbose_name='CEP')),
                ('observacoes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Local de Entrega',
                'verbose_name_plural': 'Locais de Entrega',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='pedidocompra',
            name='local_entrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_compra', to='compras.localentrega', verbose_name='Local de Entrega'),
        ),
    ]
