# Generated by Django 5.2.5 on 2025-11-01 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('abastecimentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LocalEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('tipo', models.CharField(choices=[('ALMOX', 'Almoxarifado'), ('TANQUE', 'Tanque Interno'), ('POSTO', 'Posto Externo')], max_length=10)),
                ('fornecedor_nome', models.CharField(blank=True, default='', max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadeMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=10, unique=True)),
                ('descricao', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('codigo', models.CharField(max_length=60, unique=True)),
                ('tipo', models.CharField(choices=[('PECA', 'Peça'), ('COMBUSTIVEL', 'Combustível'), ('INSUMO', 'Insumo')], max_length=12)),
                ('ativo', models.BooleanField(default=True)),
                ('densidade_kg_l', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='almoxarifado.categoriaproduto')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='almoxarifado.unidademedida')),
            ],
        ),
        migrations.CreateModel(
            name='MovimentoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída'), ('AJUSTE', 'Ajuste')], max_length=10)),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=14)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('documento', models.CharField(blank=True, default='', max_length=100)),
                ('observacao', models.TextField(blank=True, default='')),
                ('abastecimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos_estoque', to='abastecimentos.abastecimento')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='almoxarifado.localestoque')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='almoxarifado.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almoxarifado.localestoque')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almoxarifado.produto')),
            ],
            options={
                'unique_together': {('produto', 'local')},
            },
        ),
    ]
