# Generated by Django 5.2.8 on 2026-02-06 17:43

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0010_plano_assinaturacliente'),
        ('equipamentos', '0005_fix_medicao_origem_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='FioDiamantado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, verbose_name='Codigo do Fio')),
                ('fabricante', models.CharField(max_length=100, verbose_name='Fabricante')),
                ('numero_serie', models.CharField(blank=True, max_length=100, verbose_name='Numero de Serie')),
                ('comprimento_metros', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Comprimento (metros)')),
                ('perolas_por_metro', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Perolas por Metro')),
                ('diametro_inicial_mm', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Diametro Inicial (mm)')),
                ('diametro_minimo_mm', models.DecimalField(decimal_places=2, default=Decimal('6.0'), help_text='Diametro minimo antes da substituicao', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Diametro Minimo (mm)')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('FINALIZADO', 'Finalizado'), ('MANUTENCAO', 'Em Manutencao')], default='ATIVO', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observacoes')),
                ('data_cadastro', models.DateField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fios_diamantados', to='cadastro.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Fio Diamantado',
                'verbose_name_plural': 'Fios Diamantados',
                'ordering': ['-criado_em'],
                'unique_together': {('cliente', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='RegistroCorte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fonte_energia', models.CharField(choices=[('GERADOR_DIESEL', 'Gerador Diesel'), ('REDE_ELETRICA', 'Rede Eletrica')], default='REDE_ELETRICA', max_length=20, verbose_name='Fonte de Energia')),
                ('data', models.DateField(verbose_name='Data do Corte')),
                ('hora_inicial', models.TimeField(verbose_name='Hora Inicial')),
                ('hora_final', models.TimeField(verbose_name='Hora Final')),
                ('horimetro_inicial', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Horimetro Inicial')),
                ('horimetro_final', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Horimetro Final')),
                ('comprimento_corte_m', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Comprimento do Corte (m)')),
                ('altura_largura_corte_m', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Altura/Largura do Corte (m)')),
                ('diametro_inicial_mm', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Diametro Inicial do Corte (mm)')),
                ('diametro_final_mm', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Diametro Final do Corte (mm)')),
                ('area_corte_m2', models.DecimalField(decimal_places=4, editable=False, max_digits=12, verbose_name='Area do Corte (m2)')),
                ('tempo_execucao_horas', models.DecimalField(decimal_places=2, editable=False, max_digits=8, verbose_name='Tempo de Execucao (horas)')),
                ('desgaste_mm', models.DecimalField(decimal_places=2, editable=False, max_digits=6, verbose_name='Desgaste (mm)')),
                ('velocidade_corte_m2h', models.DecimalField(decimal_places=4, editable=False, max_digits=10, verbose_name='Velocidade de Corte (m2/h)')),
                ('consumo_combustivel_litros', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Consumo de Combustivel (litros)')),
                ('operador_nome', models.CharField(blank=True, max_length=100, verbose_name='Nome do Operador')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observacoes')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('fio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_corte', to='fio_diamantado.fiodiamantado', verbose_name='Fio Diamantado')),
                ('gerador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cortes_como_gerador', to='equipamentos.equipamento', verbose_name='Gerador (se diesel)')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cortes_fio_diamantado', to='equipamentos.equipamento', verbose_name='Maquina de Corte')),
            ],
            options={
                'verbose_name': 'Registro de Corte',
                'verbose_name_plural': 'Registros de Corte',
                'ordering': ['-data', '-hora_final'],
            },
        ),
    ]
