# Generated by Django 5.2.8 on 2026-02-06 19:02

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0010_plano_assinaturacliente'),
        ('equipamentos', '0005_fix_medicao_origem_max_length'),
        ('fio_diamantado', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrocorte',
            options={'ordering': ['-data', '-criado_em'], 'verbose_name': 'Registro de Corte', 'verbose_name_plural': 'Registros de Corte'},
        ),
        migrations.AddField(
            model_name='fiodiamantado',
            name='data_compra',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Compra'),
        ),
        migrations.AddField(
            model_name='fiodiamantado',
            name='empreendimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fios_diamantados', to='cadastro.empreendimento', verbose_name='Empreendimento'),
        ),
        migrations.AddField(
            model_name='fiodiamantado',
            name='localizacao',
            field=models.CharField(choices=[('ALMOXARIFADO', 'Almoxarifado'), ('EMPREENDIMENTO', 'Empreendimento'), ('MAQUINA', 'Instalado em Maquina')], default='ALMOXARIFADO', max_length=20, verbose_name='Localizacao'),
        ),
        migrations.AddField(
            model_name='fiodiamantado',
            name='maquina_instalada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fios_instalados', to='equipamentos.equipamento', verbose_name='Maquina onde esta instalado'),
        ),
        migrations.AddField(
            model_name='fiodiamantado',
            name='nota_fiscal',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nota Fiscal'),
        ),
        migrations.AddField(
            model_name='fiodiamantado',
            name='valor_por_metro',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor por Metro (R$)'),
        ),
        migrations.AddField(
            model_name='registrocorte',
            name='empreendimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cortes_fio_diamantado', to='cadastro.empreendimento', verbose_name='Empreendimento'),
        ),
        migrations.AddField(
            model_name='registrocorte',
            name='status',
            field=models.CharField(choices=[('EM_ANDAMENTO', 'Em Andamento'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='EM_ANDAMENTO', max_length=20, verbose_name='Status do Corte'),
        ),
        migrations.AlterField(
            model_name='registrocorte',
            name='altura_largura_corte_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Altura/Largura do Corte (m)'),
        ),
        migrations.AlterField(
            model_name='registrocorte',
            name='area_corte_m2',
            field=models.DecimalField(blank=True, decimal_places=4, editable=False, max_digits=12, null=True, verbose_name='Area do Corte (m2)'),
        ),
        migrations.AlterField(
            model_name='registrocorte',
            name='comprimento_corte_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Comprimento do Corte (m)'),
        ),
        migrations.AlterField(
            model_name='registrocorte',
            name='desgaste_mm',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=6, null=True, verbose_name='Desgaste (mm)'),
        ),
        migrations.AlterField(
            model_name='registrocorte',
            name='diametro_final_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Diametro Final do Corte (mm)'),
        ),
        migrations.AlterField(
            model_name='registrocorte',
            name='hora_final',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora Final'),
        ),
        migrations.AlterField(
            model_name='registrocorte',
            name='horimetro_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Horimetro Final'),
        ),
        migrations.AlterField(
            model_name='registrocorte',
            name='tempo_execucao_horas',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=8, null=True, verbose_name='Tempo de Execucao (horas)'),
        ),
        migrations.AlterField(
            model_name='registrocorte',
            name='velocidade_corte_m2h',
            field=models.DecimalField(blank=True, decimal_places=4, editable=False, max_digits=10, null=True, verbose_name='Velocidade de Corte (m2/h)'),
        ),
        migrations.CreateModel(
            name='MovimentacaoFio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada no Almoxarifado'), ('SAIDA_EMPREENDIMENTO', 'Saida para Empreendimento'), ('INSTALACAO_MAQUINA', 'Instalacao em Maquina'), ('REMOCAO_MAQUINA', 'Remocao da Maquina'), ('RETORNO_ALMOXARIFADO', 'Retorno ao Almoxarifado')], max_length=30, verbose_name='Tipo de Movimentacao')),
                ('data', models.DateField(verbose_name='Data da Movimentacao')),
                ('responsavel', models.CharField(blank=True, max_length=100, verbose_name='Responsavel pela Movimentacao')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observacoes')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empreendimento_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_fio_destino', to='cadastro.empreendimento', verbose_name='Empreendimento Destino')),
                ('empreendimento_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_fio_origem', to='cadastro.empreendimento', verbose_name='Empreendimento Origem')),
                ('fio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='fio_diamantado.fiodiamantado', verbose_name='Fio Diamantado')),
                ('maquina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_fio', to='equipamentos.equipamento', verbose_name='Maquina')),
            ],
            options={
                'verbose_name': 'Movimentacao de Fio',
                'verbose_name_plural': 'Movimentacoes de Fio',
                'ordering': ['-data', '-criado_em'],
            },
        ),
    ]
