# Generated by Django 5.2.8 on 2026-02-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fio_diamantado', '0002_add_logistica_e_fluxo_corte'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiodiamantado',
            name='fornecedor',
            field=models.CharField(blank=True, max_length=200, verbose_name='Fornecedor'),
        ),
    ]
