# Generated by Django 5.2.8 on 2026-02-08 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fio_diamantado', '0003_add_fornecedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrocorte',
            name='data_final',
            field=models.DateField(blank=True, null=True, verbose_name='Data Final'),
        ),
    ]
