# Generated by Django 5.2.8 on 2026-02-27 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fio_diamantado', '0004_add_data_final_to_registro_corte'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='registrocorte',
            name='operador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cortes_fio_diamantado', to=settings.AUTH_USER_MODEL, verbose_name='Operador (Usuário)'),
        ),
    ]
