# Generated by Django 5.2.5 on 2025-11-01 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('almoxarifado', '0001_initial'),
        ('cadastro', '0006_cliente_qr_code_empreendimento_qr_code'),
        ('equipamentos', '0003_equipamento_qr_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True)),
                ('tipo', models.CharField(choices=[('MANUTENCAO_CORRETIVA', 'Manutenção Corretiva'), ('MANUTENCAO_PREVENTIVA', 'Manutenção Preventiva'), ('PRODUTO', 'Venda de Produto')], max_length=30)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('ENVIADO', 'Enviado ao Cliente'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado'), ('CANCELADO', 'Cancelado')], default='RASCUNHO', max_length=20)),
                ('data_emissao', models.DateField(auto_now_add=True)),
                ('data_validade', models.DateField()),
                ('data_aprovacao', models.DateField(blank=True, null=True)),
                ('valor_servicos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_produtos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_deslocamento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('descricao', models.TextField(blank=True, default='')),
                ('observacoes', models.TextField(blank=True, default='')),
                ('prazo_execucao_dias', models.PositiveIntegerField(default=1, help_text='Prazo em dias para execução')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orcamentos_aprovados', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orcamentos', to='cadastro.cliente')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orcamentos_criados', to=settings.AUTH_USER_MODEL)),
                ('empreendimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orcamentos', to='cadastro.empreendimento')),
                ('equipamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orcamentos', to='equipamentos.equipamento')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SERVICO', 'Serviço'), ('PRODUTO', 'Produto')], max_length=10)),
                ('descricao', models.CharField(max_length=255)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('observacao', models.TextField(blank=True, default='')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='almoxarifado.produto')),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='orcamentos.orcamento')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='orcamento',
            index=models.Index(fields=['numero'], name='orcamentos__numero_c305b4_idx'),
        ),
        migrations.AddIndex(
            model_name='orcamento',
            index=models.Index(fields=['cliente', '-data_emissao'], name='orcamentos__cliente_a8e6f3_idx'),
        ),
        migrations.AddIndex(
            model_name='orcamento',
            index=models.Index(fields=['status'], name='orcamentos__status_3e1d3f_idx'),
        ),
    ]
