# Generated by Django 5.2.5 on 2025-11-08 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='km_deslocado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='KM Deslocado'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='valor_km',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor do KM'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='valor_deslocamento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor do Deslocamento'),
        ),
    ]
