# Generated by Django 5.2.8 on 2026-02-27 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0002_populate_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='aliquota_cofins',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Alíquota de COFINS (%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='produto',
            name='aliquota_icms',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Alíquota de ICMS (%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='produto',
            name='aliquota_ipi',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Alíquota de IPI (%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='produto',
            name='aliquota_pis',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Alíquota de PIS (%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='produto',
            name='preco_custo',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Custo do produto (opcional)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='preco_venda',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Preço de venda do produto', max_digits=12),
        ),
    ]
