# Generated by Django 5.2.6 on 2025-10-02 22:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('equipamentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True, default='')),
                ('periodicidade', models.CharField(choices=[('DIARIO', 'Diário'), ('SEMANAL', 'Semanal'), ('QUINZENAL', 'Quinzenal'), ('MENSAL', 'Mensal')], default='DIARIO', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tipo_equipamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modelos_checklist', to='equipamentos.tipoequipamento')),
            ],
            options={
                'verbose_name': 'Modelo de Checklist',
                'verbose_name_plural': 'Modelos de Checklist',
                'ordering': ['tipo_equipamento__nome', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ItemChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('categoria', models.CharField(choices=[('VISUAL', 'Inspeção Visual'), ('FUNCIONAL', 'Teste Funcional'), ('MEDICAO', 'Medição'), ('LIMPEZA', 'Limpeza'), ('LUBRIFICACAO', 'Lubrificação'), ('DOCUMENTACAO', 'Documentação'), ('SEGURANCA', 'Segurança'), ('OUTROS', 'Outros')], default='VISUAL', max_length=50)),
                ('pergunta', models.CharField(max_length=255)),
                ('descricao_ajuda', models.TextField(blank=True, default='', help_text='Instruções detalhadas para o operador')),
                ('tipo_resposta', models.CharField(choices=[('SIM_NAO', 'Sim/Não'), ('CONFORME', 'Conforme/Não Conforme'), ('NUMERO', 'Valor Numérico'), ('TEXTO', 'Texto Livre')], default='CONFORME', max_length=20)),
                ('obrigatorio', models.BooleanField(default=True)),
                ('requer_observacao_nao_conforme', models.BooleanField(default=True, help_text='Exige observação quando resposta for não conforme')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='nr12.modelochecklist')),
            ],
            options={
                'verbose_name': 'Item de Checklist',
                'verbose_name_plural': 'Itens de Checklist',
                'ordering': ['modelo', 'ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistRealizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(choices=[('WEB', 'Sistema Web'), ('BOT', 'Bot Telegram'), ('MOBILE', 'App Mobile')], default='WEB', max_length=20)),
                ('data_hora_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_hora_fim', models.DateTimeField(blank=True, null=True)),
                ('leitura_equipamento', models.DecimalField(blank=True, decimal_places=2, help_text='Leitura do horímetro/odômetro no momento do checklist', max_digits=12, null=True)),
                ('status', models.CharField(choices=[('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='EM_ANDAMENTO', max_length=20)),
                ('resultado_geral', models.CharField(blank=True, choices=[('APROVADO', 'Aprovado'), ('APROVADO_RESTRICAO', 'Aprovado com Restrição'), ('REPROVADO', 'Reprovado')], max_length=20, null=True)),
                ('observacoes_gerais', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checklists', to='equipamentos.equipamento')),
                ('operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checklists', to='core.operador')),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuário web que criou (se não for via bot)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklists_criados', to=settings.AUTH_USER_MODEL)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checklists_realizados', to='nr12.modelochecklist')),
            ],
            options={
                'verbose_name': 'Checklist Realizado',
                'verbose_name_plural': 'Checklists Realizados',
                'ordering': ['-data_hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='NotificacaoChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('NAO_CONFORMIDADE', 'Não Conformidade'), ('CHECKLIST_REPROVADO', 'Checklist Reprovado'), ('ITEM_CRITICO', 'Item Crítico')], default='NAO_CONFORMIDADE', max_length=20)),
                ('mensagem', models.TextField()),
                ('lida', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='nr12.checklistrealizado')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_checklist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificação de Checklist',
                'verbose_name_plural': 'Notificações de Checklist',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='RespostaItemChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.CharField(blank=True, choices=[('CONFORME', 'Conforme'), ('NAO_CONFORME', 'Não Conforme'), ('SIM', 'Sim'), ('NAO', 'Não'), ('NA', 'Não Aplicável')], max_length=20, null=True)),
                ('valor_numerico', models.DecimalField(blank=True, decimal_places=2, help_text='Para respostas do tipo numérico', max_digits=10, null=True)),
                ('valor_texto', models.TextField(blank=True, default='', help_text='Para respostas do tipo texto livre')),
                ('observacao', models.TextField(blank=True, default='', help_text='Observações adicionais, obrigatório para não conformidades')),
                ('foto', models.ImageField(blank=True, help_text='Foto da não conformidade ou evidência', null=True, upload_to='checklists/%Y/%m/')),
                ('data_hora_resposta', models.DateTimeField(auto_now_add=True)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='nr12.checklistrealizado')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respostas', to='nr12.itemchecklist')),
            ],
            options={
                'verbose_name': 'Resposta de Item',
                'verbose_name_plural': 'Respostas de Itens',
                'ordering': ['checklist', 'item__ordem'],
                'unique_together': {('checklist', 'item')},
            },
        ),
    ]
