# Generated by Django 5.2.5 on 2025-11-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nr12', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistrealizado',
            name='operador_nome',
            field=models.CharField(blank=True, default='', help_text='Nome do operador quando não há operador cadastrado', max_length=200),
        ),
    ]
