# Generated by Django 5.2.5 on 2025-11-05 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0006_cliente_qr_code_empreendimento_qr_code'),
        ('core', '0003_supervisor_endereco_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='operador',
            name='empreendimentos_vinculados',
            field=models.ManyToManyField(blank=True, related_name='operadores_vinculados', to='cadastro.empreendimento', verbose_name='Empreendimentos'),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='empreendimentos_vinculados',
            field=models.ManyToManyField(blank=True, related_name='supervisores_vinculados', to='cadastro.empreendimento', verbose_name='Empreendimentos'),
        ),
    ]
