# Generated by Django 5.2.4 on 2026-01-24 11:03

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_supervisor_user_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisor',
            name='user',
        ),
        migrations.AlterField(
            model_name='operador',
            name='cpf',
            field=models.CharField(help_text='Formato: 000.000.000-00', max_length=14, unique=True, validators=[core.validators.validate_cpf], verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='cpf',
            field=models.CharField(help_text='Formato: 000.000.000-00', max_length=14, unique=True, validators=[core.validators.validate_cpf], verbose_name='CPF'),
        ),
    ]
