# Generated by Django 5.2.4 on 2026-01-28 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_supervisor_user_alter_operador_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('SUPERVISOR', 'Supervisor'), ('OPERADOR', 'Operador'), ('TECNICO', 'Técnico'), ('FINANCEIRO', 'Financeiro'), ('COMPRAS', 'Compras'), ('CLIENTE', 'Cliente')], default='ADMIN', max_length=20),
        ),
    ]
