# Generated by Django 5.2.8 on 2026-02-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_operador_user_supervisor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='operador',
            name='funcao',
            field=models.CharField(blank=True, help_text='Ex: Operador de Escavadeira, Operador de Pá Carregadeira', max_length=100, verbose_name='Função'),
        ),
        migrations.AddField(
            model_name='operador',
            name='matricula',
            field=models.CharField(blank=True, help_text='Número de matrícula do funcionário', max_length=50, verbose_name='Matrícula'),
        ),
        migrations.AddField(
            model_name='operador',
            name='nr12_certificado',
            field=models.FileField(blank=True, help_text='Upload do certificado em PDF ou imagem', null=True, upload_to='operadores/certificados/%Y/%m/', verbose_name='Certificado NR12'),
        ),
        migrations.AddField(
            model_name='operador',
            name='nr12_curso_carga_horaria',
            field=models.PositiveIntegerField(blank=True, help_text='Carga horária do curso de formação', null=True, verbose_name='Carga Horária (horas)'),
        ),
        migrations.AddField(
            model_name='operador',
            name='nr12_curso_data_conclusao',
            field=models.DateField(blank=True, help_text='Data de conclusão do curso de formação NR12', null=True, verbose_name='Data Conclusão Curso NR12'),
        ),
        migrations.AddField(
            model_name='operador',
            name='nr12_entidade_formadora',
            field=models.CharField(blank=True, help_text='Nome da entidade que ministrou o curso', max_length=200, verbose_name='Entidade Formadora'),
        ),
        migrations.AddField(
            model_name='operador',
            name='nr12_reciclagem_certificado',
            field=models.FileField(blank=True, help_text='Upload do certificado de reciclagem', null=True, upload_to='operadores/reciclagens/%Y/%m/', verbose_name='Certificado Reciclagem'),
        ),
        migrations.AddField(
            model_name='operador',
            name='nr12_reciclagem_vencimento',
            field=models.DateField(blank=True, help_text='Data de vencimento da reciclagem NR12', null=True, verbose_name='Vencimento da Reciclagem'),
        ),
    ]
