# Generated by Django 5.2.5 on 2025-11-01 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('almoxarifado', '0001_initial'),
        ('cadastro', '0006_cliente_qr_code_empreendimento_qr_code'),
        ('core', '0003_supervisor_endereco_fields'),
        ('equipamentos', '0003_equipamento_qr_code'),
        ('orcamentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('EM_EXECUCAO', 'Em Execução'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='ABERTA', max_length=20)),
                ('data_abertura', models.DateField(auto_now_add=True)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_conclusao', models.DateField(blank=True, null=True)),
                ('data_prevista', models.DateField()),
                ('valor_servicos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_produtos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_deslocamento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_adicional', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_final', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('descricao', models.TextField(blank=True, default='')),
                ('observacoes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aberto_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_servico_abertas', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_servico', to='cadastro.cliente')),
                ('concluido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_servico_concluidas', to=settings.AUTH_USER_MODEL)),
                ('empreendimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordens_servico', to='cadastro.empreendimento')),
                ('equipamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordens_servico', to='equipamentos.equipamento')),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_servico', to='orcamentos.orcamento')),
                ('tecnico_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_servico_responsavel', to='core.operador')),
            ],
            options={
                'verbose_name': 'Ordem de Serviço',
                'verbose_name_plural': 'Ordens de Serviço',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemOrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SERVICO', 'Serviço'), ('PRODUTO', 'Produto')], max_length=10)),
                ('descricao', models.CharField(max_length=255)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('observacao', models.TextField(blank=True, default='')),
                ('executado', models.BooleanField(default=False)),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='almoxarifado.produto')),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='ordens_servico.ordemservico')),
            ],
            options={
                'verbose_name': 'Item da Ordem de Serviço',
                'verbose_name_plural': 'Itens da Ordem de Serviço',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='ordemservico',
            index=models.Index(fields=['numero'], name='ordens_serv_numero_636ae3_idx'),
        ),
        migrations.AddIndex(
            model_name='ordemservico',
            index=models.Index(fields=['status'], name='ordens_serv_status_ad9cd1_idx'),
        ),
        migrations.AddIndex(
            model_name='ordemservico',
            index=models.Index(fields=['cliente', '-data_abertura'], name='ordens_serv_cliente_8dfaf9_idx'),
        ),
    ]
