# Generated by Django 5.2.5 on 2025-11-08 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens_servico', '0001_initial'),
        ('tecnicos', '0003_tecnico_clientes_tecnico_empreendimentos_vinculados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='tecnico_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_servico_responsavel', to='tecnicos.tecnico'),
        ),
    ]
