# Generated by Django 5.2.5 on 2025-10-29 21:33

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import manutencao.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipamentos', '0003_equipamento_qr_code'),
        ('tecnicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('preventiva', 'Preventiva'), ('corretiva', 'Corretiva')], max_length=20)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('horimetro', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('descricao', models.TextField(blank=True, default='')),
                ('observacoes', models.TextField(blank=True, default='')),
                ('proxima_manutencao', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutencoes', to='equipamentos.equipamento')),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manutencoes', to='tecnicos.tecnico')),
            ],
            options={
                'ordering': ['-data', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AnexoManutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to=manutencao.models.manutencao_attachment_path)),
                ('nome_original', models.CharField(blank=True, default='', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('manutencao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='manutencao.manutencao')),
            ],
        ),
        migrations.AddIndex(
            model_name='manutencao',
            index=models.Index(fields=['equipamento', 'data'], name='manutencao__equipam_fc5ca0_idx'),
        ),
        migrations.AddIndex(
            model_name='manutencao',
            index=models.Index(fields=['equipamento', 'horimetro'], name='manutencao__equipam_7e7498_idx'),
        ),
    ]
