# Generated by Django 5.2.4 on 2026-01-01 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0002_alter_proxima_manutencao_to_decimal'),
        ('ordens_servico', '0003_ordemservico_horimetro_final_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manutencao',
            name='ordem_servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manutencoes', to='ordens_servico.ordemservico'),
        ),
    ]
