# Generated by Django 5.2.5 on 2025-11-01 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0006_cliente_qr_code_empreendimento_qr_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True)),
                ('tipo', models.CharField(choices=[('FORNECEDOR', 'Fornecedor'), ('SALARIO', 'Salário'), ('IMPOSTO', 'Imposto'), ('ALUGUEL', 'Aluguel'), ('SERVICO', 'Serviço'), ('OUTROS', 'Outros')], max_length=30)),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('PAGA', 'Paga'), ('VENCIDA', 'Vencida'), ('CANCELADA', 'Cancelada')], default='ABERTA', max_length=20)),
                ('fornecedor', models.CharField(max_length=200)),
                ('documento_fornecedor', models.CharField(blank=True, default='', max_length=20)),
                ('data_emissao', models.DateField(auto_now_add=True)),
                ('data_vencimento', models.DateField()),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('valor_original', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_juros', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_final', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('descricao', models.TextField(blank=True, default='')),
                ('observacoes', models.TextField(blank=True, default='')),
                ('numero_documento', models.CharField(blank=True, default='', max_length=50)),
                ('forma_pagamento', models.CharField(blank=True, default='', max_length=50)),
                ('comprovante', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_pagar_criadas', to=settings.AUTH_USER_MODEL)),
                ('pago_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_pagar_pagas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conta a Pagar',
                'verbose_name_plural': 'Contas a Pagar',
                'ordering': ['-data_vencimento'],
            },
        ),
        migrations.CreateModel(
            name='ContaReceber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True)),
                ('tipo', models.CharField(choices=[('ORCAMENTO_PRODUTO', 'Orçamento de Produto'), ('ORDEM_SERVICO', 'Ordem de Serviço'), ('VENDA', 'Venda Direta'), ('OUTROS', 'Outros')], max_length=30)),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('PAGA', 'Paga'), ('VENCIDA', 'Vencida'), ('CANCELADA', 'Cancelada')], default='ABERTA', max_length=20)),
                ('data_emissao', models.DateField(auto_now_add=True)),
                ('data_vencimento', models.DateField()),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('valor_original', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_juros', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_final', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('descricao', models.TextField(blank=True, default='')),
                ('observacoes', models.TextField(blank=True, default='')),
                ('forma_pagamento', models.CharField(blank=True, default='', max_length=50)),
                ('comprovante', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contas_receber', to='cadastro.cliente')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_receber_criadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conta a Receber',
                'verbose_name_plural': 'Contas a Receber',
                'ordering': ['-data_vencimento'],
            },
        ),
    ]
