# Generated by Django 5.2.5 on 2025-11-01 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financeiro', '0001_initial'),
        ('orcamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contareceber',
            name='orcamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contas_receber', to='orcamentos.orcamento'),
        ),
    ]
