# Generated by Django 5.2.5 on 2025-11-01 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financeiro', '0002_initial'),
        ('ordens_servico', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contareceber',
            name='ordem_servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contas_receber', to='ordens_servico.ordemservico'),
        ),
        migrations.AddField(
            model_name='contareceber',
            name='recebido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_receber_recebidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='contapagar',
            index=models.Index(fields=['numero'], name='financeiro__numero_20246c_idx'),
        ),
        migrations.AddIndex(
            model_name='contapagar',
            index=models.Index(fields=['status'], name='financeiro__status_9cb6c1_idx'),
        ),
        migrations.AddIndex(
            model_name='contapagar',
            index=models.Index(fields=['data_vencimento'], name='financeiro__data_ve_5ce5b9_idx'),
        ),
        migrations.AddIndex(
            model_name='contapagar',
            index=models.Index(fields=['fornecedor'], name='financeiro__fornece_9432ee_idx'),
        ),
        migrations.AddIndex(
            model_name='contareceber',
            index=models.Index(fields=['numero'], name='financeiro__numero_a77fb4_idx'),
        ),
        migrations.AddIndex(
            model_name='contareceber',
            index=models.Index(fields=['status'], name='financeiro__status_36b422_idx'),
        ),
        migrations.AddIndex(
            model_name='contareceber',
            index=models.Index(fields=['cliente', '-data_vencimento'], name='financeiro__cliente_838023_idx'),
        ),
        migrations.AddIndex(
            model_name='contareceber',
            index=models.Index(fields=['data_vencimento'], name='financeiro__data_ve_9e57f0_idx'),
        ),
    ]
