# Generated by Django 5.2.4 on 2025-12-30 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True)),
                ('tipo_pagamento', models.CharField(choices=[('TOTAL', 'Pagamento Total'), ('ADIANTAMENTO', 'Adiantamento'), ('PARCIAL', 'Pagamento Parcial')], max_length=20)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONFIRMADO', 'Confirmado'), ('CANCELADO', 'Cancelado')], default='CONFIRMADO', max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_final', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('forma_pagamento', models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('PIX', 'PIX'), ('CHEQUE', 'Cheque'), ('BOLETO', 'Boleto Bancário'), ('DEPOSITO', 'Depósito Bancário'), ('TRANSFERENCIA', 'Transferência Bancária'), ('CARTAO_CREDITO', 'Cartão de Crédito'), ('CARTAO_DEBITO', 'Cartão de Débito')], max_length=30)),
                ('data_pagamento', models.DateField()),
                ('numero_parcela', models.IntegerField(blank=True, null=True)),
                ('total_parcelas', models.IntegerField(blank=True, null=True)),
                ('numero_cheque', models.CharField(blank=True, default='', max_length=50)),
                ('banco_cheque', models.CharField(blank=True, default='', max_length=100)),
                ('data_compensacao', models.DateField(blank=True, null=True)),
                ('numero_documento', models.CharField(blank=True, default='', max_length=100)),
                ('comprovante', models.CharField(blank=True, default='', max_length=200)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conta_receber', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to='financeiro.contareceber')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamentos_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-data_pagamento', '-created_at'],
                'indexes': [models.Index(fields=['numero'], name='financeiro__numero_f501ee_idx'), models.Index(fields=['conta_receber', '-data_pagamento'], name='financeiro__conta_r_109155_idx'), models.Index(fields=['data_pagamento'], name='financeiro__data_pa_da0b18_idx'), models.Index(fields=['forma_pagamento'], name='financeiro__forma_p_bbfc94_idx'), models.Index(fields=['status'], name='financeiro__status_7b0dcf_idx')],
            },
        ),
    ]
