# Generated by Django 5.2.6 on 2025-09-30 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.CharField(blank=True, default='', max_length=255)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descricao', models.CharField(blank=True, default='', max_length=150)),
                ('fabricante', models.CharField(blank=True, default='', max_length=100)),
                ('modelo', models.CharField(blank=True, default='', max_length=100)),
                ('ano_fabricacao', models.IntegerField(blank=True, null=True)),
                ('numero_serie', models.CharField(blank=True, default='', max_length=100)),
                ('tipo_medicao', models.CharField(choices=[('KM', 'Quilômetro'), ('HORA', 'Horímetro')], default='HORA', max_length=4)),
                ('leitura_atual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipamentos', to='cadastro.cliente')),
                ('empreendimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipamentos', to='cadastro.empreendimento')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipamentos', to='equipamentos.tipoequipamento')),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='MedicaoEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(choices=[('CHECKLIST', 'Checklist'), ('ABASTECIMENTO', 'Abastecimento'), ('MANUTENCAO', 'Manutenção'), ('MANUAL', 'Manual')], default='MANUAL', max_length=20)),
                ('leitura', models.DecimalField(decimal_places=2, max_digits=12)),
                ('observacao', models.CharField(blank=True, default='', max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicoes', to='equipamentos.equipamento')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='PlanoManutencaoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('modo', models.CharField(choices=[('KM', 'KM'), ('HORA', 'HORA'), ('DIAS', 'DIAS')], max_length=10)),
                ('periodicidade_valor', models.PositiveIntegerField()),
                ('leitura_base', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('data_base', models.DateField(blank=True, null=True)),
                ('proxima_leitura', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('proxima_data', models.DateField(blank=True, null=True)),
                ('antecedencia_percent', models.PositiveSmallIntegerField(default=10)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos', to='equipamentos.equipamento')),
            ],
            options={
                'ordering': ['titulo'],
            },
        ),
    ]
