# Generated by Django 5.2.5 on 2025-10-29 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0002_add_uuid_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/equipamentos/', verbose_name='QR Code'),
        ),
    ]
