# Generated by Django 5.2.8 on 2026-02-14 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nr12', '0005_add_cliente_to_modelochecklist'),
        ('orcamentos', '0002_orcamento_km_deslocado_orcamento_valor_km_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='modelo_manutencao_preventiva',
            field=models.ForeignKey(blank=True, help_text='Modelo de manutenção preventiva. Obrigatório quando tipo = MANUTENCAO_PREVENTIVA', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orcamentos', to='nr12.modelomanutencaopreventiva'),
        ),
    ]
