# Generated by Django 5.2.8 on 2026-02-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0003_add_modelo_manutencao_preventiva'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='horimetro',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Leitura do horímetro ou odômetro no momento do orçamento', max_digits=10, null=True, verbose_name='Horímetro/Odômetro'),
        ),
    ]
