# Generated by Django 5.2.8 on 2026-02-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0017_itemmanutencao'),
        ('orcamentos', '0004_orcamento_horimetro'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='itens_manutencao',
            field=models.ManyToManyField(blank=True, help_text='Itens de manutenção (filtros, óleos, etc.) incluídos neste orçamento', related_name='orcamentos', to='equipamentos.itemmanutencao'),
        ),
    ]
