# Generated by Django 5.2.8 on 2026-02-27 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, unique=True)),
                ('descricao', models.TextField(blank=True, default='')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoria de Serviço',
                'verbose_name_plural': 'Categorias de Serviços',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único do serviço', max_length=60, unique=True)),
                ('nome', models.CharField(help_text='Nome/descrição do serviço', max_length=200)),
                ('descricao_detalhada', models.TextField(blank=True, default='', help_text='Descrição completa do serviço')),
                ('preco_venda', models.DecimalField(decimal_places=2, default=0, help_text='Preço de venda do serviço', max_digits=12)),
                ('preco_custo', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Custo estimado do serviço (opcional)', max_digits=12, null=True)),
                ('aliquota_iss', models.DecimalField(decimal_places=2, default=0, help_text='Alíquota de ISS (%)', max_digits=5)),
                ('aliquota_pis', models.DecimalField(decimal_places=2, default=0, help_text='Alíquota de PIS (%)', max_digits=5)),
                ('aliquota_cofins', models.DecimalField(decimal_places=2, default=0, help_text='Alíquota de COFINS (%)', max_digits=5)),
                ('aliquota_csll', models.DecimalField(decimal_places=2, default=0, help_text='Alíquota de CSLL (%)', max_digits=5)),
                ('aliquota_irpj', models.DecimalField(decimal_places=2, default=0, help_text='Alíquota de IRPJ (%)', max_digits=5)),
                ('unidade', models.CharField(choices=[('HORA', 'Hora'), ('DIA', 'Dia'), ('MES', 'Mês'), ('SERVICO', 'Serviço'), ('VISITA', 'Visita')], default='SERVICO', help_text='Unidade de medida do serviço', max_length=20)),
                ('tempo_estimado', models.IntegerField(blank=True, help_text='Tempo estimado de execução em minutos', null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicos', to='servicos.categoriaservico')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'ordering': ['nome'],
            },
        ),
    ]
