# Generated by Django 5.2.8 on 2025-11-16 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnicos', '0003_tecnico_clientes_tecnico_empreendimentos_vinculados'),
    ]

    operations = [
        migrations.AddField(
            model_name='tecnico',
            name='codigo_valido_ate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Código válido até'),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='codigo_vinculacao',
            field=models.CharField(blank=True, help_text='Código de 8 dígitos para vincular Telegram', max_length=8, null=True, unique=True, verbose_name='Código de Vinculação'),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='ID único do chat do Telegram', max_length=50, null=True, unique=True, verbose_name='Telegram Chat ID'),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='telegram_username',
            field=models.CharField(blank=True, default='', help_text='@username do técnico no Telegram', max_length=100, verbose_name='Username do Telegram'),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='telegram_vinculado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de vinculação do Telegram'),
        ),
    ]
