# Generated by Django 5.2.8 on 2026-02-12 20:06

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnicos', '0005_tecnico_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tecnico',
            name='cpf',
            field=models.CharField(blank=True, help_text='Formato: 000.000.000-00', max_length=14, null=True, unique=True, validators=[core.validators.validate_cpf], verbose_name='CPF'),
        ),
    ]
