# Generated by Django 5.2.4 on 2025-11-22 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0003_equipamento_qr_code'),
        ('manutencao', '0001_initial'),
        ('nr12', '0002_checklistrealizado_operador_nome'),
        ('tecnicos', '0004_tecnico_codigo_valido_ate_tecnico_codigo_vinculacao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloManutencaoPreventiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Manutenção 250h, Manutenção 500h, Revisão 10.000 km', max_length=150)),
                ('descricao', models.TextField(blank=True, default='')),
                ('tipo_medicao', models.CharField(choices=[('HORIMETRO', 'Horímetro'), ('ODOMETRO', 'Odômetro (KM)')], default='HORIMETRO', help_text='Tipo de medição para agendar a manutenção', max_length=20)),
                ('intervalo', models.DecimalField(decimal_places=2, help_text='Intervalo em horas ou KM para executar a manutenção', max_digits=10)),
                ('tolerancia', models.DecimalField(decimal_places=2, default=0, help_text='Tolerância antes de considerar atrasado (ex: 10h ou 100km)', max_digits=10)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tipo_equipamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modelos_manutencao_preventiva', to='equipamentos.tipoequipamento')),
            ],
            options={
                'verbose_name': 'Modelo de Manutenção Preventiva',
                'verbose_name_plural': 'Modelos de Manutenção Preventiva',
                'ordering': ['tipo_equipamento__nome', 'intervalo', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ItemManutencaoPreventiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('categoria', models.CharField(choices=[('TROCA_OLEO', 'Troca de Óleo'), ('TROCA_FILTRO', 'Troca de Filtro'), ('LUBRIFICACAO', 'Lubrificação'), ('INSPECAO', 'Inspeção'), ('AJUSTE', 'Ajuste/Regulagem'), ('LIMPEZA', 'Limpeza'), ('SUBSTITUICAO', 'Substituição de Peças'), ('TESTE', 'Teste Funcional'), ('MEDICAO', 'Medição'), ('OUTROS', 'Outros')], default='INSPECAO', max_length=50)),
                ('descricao', models.CharField(help_text='Ex: Trocar óleo do motor, Verificar nível de fluido hidráulico', max_length=255)),
                ('instrucoes', models.TextField(blank=True, default='', help_text='Instruções detalhadas para o técnico')),
                ('tipo_resposta', models.CharField(choices=[('EXECUTADO', 'Executado/Não Executado'), ('CONFORME', 'Conforme/Não Conforme'), ('NUMERO', 'Valor Numérico'), ('TEXTO', 'Texto Livre')], default='EXECUTADO', max_length=20)),
                ('obrigatorio', models.BooleanField(default=True)),
                ('requer_observacao_nao_conforme', models.BooleanField(default=True, help_text='Exige observação quando não executado ou não conforme')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='nr12.modelomanutencaopreventiva')),
            ],
            options={
                'verbose_name': 'Item de Manutenção Preventiva',
                'verbose_name_plural': 'Itens de Manutenção Preventiva',
                'ordering': ['modelo', 'ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProgramacaoManutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leitura_inicial', models.DecimalField(decimal_places=2, help_text='Leitura (horímetro/KM) quando a programação foi criada', max_digits=12)),
                ('leitura_ultima_manutencao', models.DecimalField(decimal_places=2, help_text='Leitura da última manutenção realizada', max_digits=12)),
                ('leitura_proxima_manutencao', models.DecimalField(decimal_places=2, help_text='Leitura prevista para a próxima manutenção', max_digits=12)),
                ('status', models.CharField(choices=[('ATIVA', 'Ativa'), ('PENDENTE', 'Pendente'), ('EM_ATRASO', 'Em Atraso'), ('INATIVA', 'Inativa')], default='ATIVA', max_length=20)),
                ('ativo', models.BooleanField(default=True, help_text='Programação ativa no sistema')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programacoes_manutencao', to='equipamentos.equipamento')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programacoes', to='nr12.modelomanutencaopreventiva')),
            ],
            options={
                'verbose_name': 'Programação de Manutenção',
                'verbose_name_plural': 'Programações de Manutenção',
                'ordering': ['equipamento', 'leitura_proxima_manutencao'],
            },
        ),
        migrations.CreateModel(
            name='ManutencaoPreventivaRealizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tecnico_nome', models.CharField(blank=True, default='', help_text='Nome do técnico quando não há técnico cadastrado', max_length=200)),
                ('origem', models.CharField(choices=[('WEB', 'Sistema Web'), ('BOT', 'Bot Telegram'), ('MOBILE', 'App Mobile')], default='WEB', max_length=20)),
                ('data_hora_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_hora_fim', models.DateTimeField(blank=True, null=True)),
                ('leitura_equipamento', models.DecimalField(decimal_places=2, help_text='Leitura do horímetro/odômetro no momento da manutenção', max_digits=12)),
                ('status', models.CharField(choices=[('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='EM_ANDAMENTO', max_length=20)),
                ('resultado_geral', models.CharField(blank=True, choices=[('COMPLETA', 'Completa'), ('COMPLETA_RESTRICAO', 'Completa com Restrição'), ('INCOMPLETA', 'Incompleta')], help_text='Resultado baseado nos itens executados', max_length=20, null=True)),
                ('observacoes_gerais', models.TextField(blank=True, default='', help_text='Observações gerais sobre a manutenção')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manutencoes_preventivas', to='equipamentos.equipamento')),
                ('manutencao', models.OneToOneField(blank=True, help_text='Registro de manutenção associado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manutencao_preventiva_realizada', to='manutencao.manutencao')),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manutencoes_preventivas', to='tecnicos.tecnico')),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuário web que criou (se não for via bot)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manutencoes_preventivas_criadas', to=settings.AUTH_USER_MODEL)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manutencoes_realizadas', to='nr12.modelomanutencaopreventiva')),
                ('programacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manutencoes_realizadas', to='nr12.programacaomanutencao')),
            ],
            options={
                'verbose_name': 'Manutenção Preventiva Realizada',
                'verbose_name_plural': 'Manutenções Preventivas Realizadas',
                'ordering': ['-data_hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='RespostaItemManutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.CharField(blank=True, choices=[('EXECUTADO', 'Executado'), ('NAO_EXECUTADO', 'Não Executado'), ('CONFORME', 'Conforme'), ('NAO_CONFORME', 'Não Conforme'), ('NA', 'Não Aplicável')], max_length=20, null=True)),
                ('valor_numerico', models.DecimalField(blank=True, decimal_places=2, help_text='Para respostas do tipo numérico', max_digits=10, null=True)),
                ('valor_texto', models.TextField(blank=True, default='', help_text='Para respostas do tipo texto livre')),
                ('observacao', models.TextField(blank=True, default='', help_text='Observações sobre a execução do item')),
                ('foto', models.ImageField(blank=True, help_text='Foto da evidência ou problema encontrado', null=True, upload_to='manutencoes_preventivas/%Y/%m/')),
                ('data_hora_resposta', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respostas', to='nr12.itemmanutencaopreventiva')),
                ('manutencao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='nr12.manutencaopreventivarealizada')),
            ],
            options={
                'verbose_name': 'Resposta de Item de Manutenção',
                'verbose_name_plural': 'Respostas de Itens de Manutenção',
                'ordering': ['manutencao', 'item__ordem'],
            },
        ),
        migrations.AddIndex(
            model_name='modelomanutencaopreventiva',
            index=models.Index(fields=['tipo_equipamento', 'ativo'], name='nr12_modelo_tipo_eq_346716_idx'),
        ),
        migrations.AddIndex(
            model_name='programacaomanutencao',
            index=models.Index(fields=['equipamento', 'status'], name='nr12_progra_equipam_ec1847_idx'),
        ),
        migrations.AddIndex(
            model_name='programacaomanutencao',
            index=models.Index(fields=['status', 'leitura_proxima_manutencao'], name='nr12_progra_status_3bfd3c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='programacaomanutencao',
            unique_together={('equipamento', 'modelo')},
        ),
        migrations.AddIndex(
            model_name='manutencaopreventivarealizada',
            index=models.Index(fields=['equipamento', '-data_hora_inicio'], name='nr12_manute_equipam_48ad55_idx'),
        ),
        migrations.AddIndex(
            model_name='manutencaopreventivarealizada',
            index=models.Index(fields=['status'], name='nr12_manute_status_d0e28e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='respostaitemmanutencao',
            unique_together={('manutencao', 'item')},
        ),
    ]
