# Generated by Django 5.2.4 on 2026-01-24 11:03

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_supervisor_user_alter_operador_cpf_and_more'),
        ('equipamentos', '0004_historicalequipamento'),
        ('nr12', '0003_modelomanutencaopreventiva_itemmanutencaopreventiva_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalChecklistRealizado',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('operador_nome', models.CharField(blank=True, default='', help_text='Nome do operador quando não há operador cadastrado', max_length=200)),
                ('origem', models.CharField(choices=[('WEB', 'Sistema Web'), ('BOT', 'Bot Telegram'), ('MOBILE', 'App Mobile')], default='WEB', max_length=20)),
                ('data_hora_inicio', models.DateTimeField(blank=True, editable=False)),
                ('data_hora_fim', models.DateTimeField(blank=True, null=True)),
                ('leitura_equipamento', models.DecimalField(blank=True, decimal_places=2, help_text='Leitura do horímetro/odômetro no momento do checklist', max_digits=12, null=True)),
                ('status', models.CharField(choices=[('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='EM_ANDAMENTO', max_length=20)),
                ('resultado_geral', models.CharField(blank=True, choices=[('APROVADO', 'Aprovado'), ('APROVADO_RESTRICAO', 'Aprovado com Restrição'), ('REPROVADO', 'Reprovado')], max_length=20, null=True)),
                ('observacoes_gerais', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(blank=True, editable=False)),
                ('atualizado_em', models.DateTimeField(blank=True, editable=False)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('equipamento', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='equipamentos.equipamento')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modelo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nr12.modelochecklist')),
                ('operador', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.operador')),
                ('usuario', models.ForeignKey(blank=True, db_constraint=False, help_text='Usuário web que criou (se não for via bot)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Checklist Realizado',
                'verbose_name_plural': 'historical Checklists Realizados',
                'db_table': 'nr12_checklistrealizado_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
