# Generated by Django 5.2.8 on 2026-02-13 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0010_plano_assinaturacliente'),
        ('nr12', '0004_historicalchecklistrealizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelochecklist',
            name='cliente',
            field=models.ForeignKey(blank=True, help_text='Cliente dono do modelo. Se vazio, é um modelo global (admin).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modelos_checklist', to='cadastro.cliente'),
        ),
    ]
