# Generated by Django 5.2.8 on 2026-02-16 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nr12', '0005_add_cliente_to_modelochecklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistrealizado',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Latitude onde o checklist foi realizado', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='checklistrealizado',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Longitude onde o checklist foi realizado', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='checklistrealizado',
            name='precisao_gps',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precisão do GPS em metros', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='historicalchecklistrealizado',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Latitude onde o checklist foi realizado', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalchecklistrealizado',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Longitude onde o checklist foi realizado', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalchecklistrealizado',
            name='precisao_gps',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precisão do GPS em metros', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='manutencaopreventivarealizada',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Latitude onde a manutenção foi realizada', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='manutencaopreventivarealizada',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Longitude onde a manutenção foi realizada', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='manutencaopreventivarealizada',
            name='precisao_gps',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precisão do GPS em metros', max_digits=8, null=True),
        ),
    ]
