# Generated by Django 5.2.8 on 2026-02-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nr12', '0006_add_geolocalizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistrealizado',
            name='geofence_distancia',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Distância em metros do local do checklist até o empreendimento', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='checklistrealizado',
            name='geofence_validado',
            field=models.BooleanField(blank=True, help_text='Se o checklist foi realizado dentro do raio de geofence do empreendimento', null=True),
        ),
        migrations.AddField(
            model_name='historicalchecklistrealizado',
            name='geofence_distancia',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Distância em metros do local do checklist até o empreendimento', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalchecklistrealizado',
            name='geofence_validado',
            field=models.BooleanField(blank=True, help_text='Se o checklist foi realizado dentro do raio de geofence do empreendimento', null=True),
        ),
    ]
