# Generated by Django 5.2.8 on 2026-02-17 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nr12', '0007_add_geofence_checklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemchecklist',
            name='foto_obrigatoria',
            field=models.BooleanField(default=False, help_text='Exige foto como evidência ao responder este item'),
        ),
        migrations.AlterField(
            model_name='checklistrealizado',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Latitude onde o checklist foi realizado', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='checklistrealizado',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Longitude onde o checklist foi realizado', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='historicalchecklistrealizado',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Latitude onde o checklist foi realizado', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='historicalchecklistrealizado',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Longitude onde o checklist foi realizado', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='manutencaopreventivarealizada',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Latitude onde a manutenção foi realizada', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='manutencaopreventivarealizada',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Longitude onde a manutenção foi realizada', max_digits=12, null=True),
        ),
    ]
