# Generated by Django 5.2.8 on 2026-02-17 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nr12', '0008_add_foto_obrigatoria_and_fix_gps_precision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistrealizado',
            name='precisao_gps',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precisão do GPS em metros', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalchecklistrealizado',
            name='precisao_gps',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precisão do GPS em metros', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='manutencaopreventivarealizada',
            name='precisao_gps',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precisão do GPS em metros', max_digits=10, null=True),
        ),
    ]
