# Generated by Django 5.2.8 on 2026-02-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0017_itemmanutencao'),
        ('nr12', '0009_fix_precisao_gps_max_digits'),
    ]

    operations = [
        migrations.AddField(
            model_name='programacaomanutencao',
            name='itens_manutencao',
            field=models.ManyToManyField(blank=True, help_text='Itens de manutenção (filtros, óleos, etc.) a serem executados', related_name='programacoes', to='equipamentos.itemmanutencao'),
        ),
    ]
