# Generated by Django 5.2.4 on 2025-11-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tecnico',
            options={'ordering': ['nome', 'nome_completo'], 'verbose_name': 'Técnico', 'verbose_name_plural': 'Técnicos'},
        ),
        migrations.AddField(
            model_name='tecnico',
            name='bairro',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='categoria_cnh',
            field=models.CharField(blank=True, default='', help_text='Ex: B, C, D, E', max_length=5, verbose_name='Categoria CNH'),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='cep',
            field=models.CharField(blank=True, default='', max_length=9, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='certificacoes',
            field=models.TextField(blank=True, default='', help_text='Liste as certificações relevantes (uma por linha)', verbose_name='Certificações'),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='cidade',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='complemento',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='cpf',
            field=models.CharField(blank=True, help_text='Formato: 000.000.000-00', max_length=14, null=True, unique=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='cursos_treinamentos',
            field=models.TextField(blank=True, default='', help_text='Liste cursos e treinamentos realizados', verbose_name='Cursos e Treinamentos'),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='documento_certificados',
            field=models.FileField(blank=True, null=True, upload_to='tecnicos/documentos/certificados/', verbose_name='Certificados (PDF)'),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='documento_cnh',
            field=models.FileField(blank=True, null=True, upload_to='tecnicos/documentos/cnh/', verbose_name='Documento CNH'),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='especialidade',
            field=models.CharField(blank=True, default='', help_text='Ex: Mecânica Diesel, Hidráulica, Elétrica, etc.', max_length=100, verbose_name='Especialidade Principal'),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='tecnicos/%Y/%m/', verbose_name='Foto'),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='logradouro',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Logradouro'),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='nivel_experiencia',
            field=models.CharField(blank=True, choices=[('JUNIOR', 'Júnior'), ('PLENO', 'Pleno'), ('SENIOR', 'Sênior'), ('ESPECIALISTA', 'Especialista')], default='PLENO', max_length=20, verbose_name='Nível de Experiência'),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='nome_completo',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Nome Completo'),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='numero',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='numero_cnh',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Número CNH'),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='observacoes',
            field=models.TextField(blank=True, default='', help_text='Informações adicionais sobre o técnico', verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='rg',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='RG'),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='telefone_emergencia',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Telefone de Emergência'),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='uf',
            field=models.CharField(blank=True, default='', max_length=2, verbose_name='UF'),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='validade_cnh',
            field=models.DateField(blank=True, null=True, verbose_name='Validade da CNH'),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='nome',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='telefone',
            field=models.CharField(blank=True, help_text='Formato: (00) 00000-0000', max_length=30, null=True, verbose_name='Telefone'),
        ),
        migrations.AddIndex(
            model_name='tecnico',
            index=models.Index(fields=['nome_completo'], name='tecnicos_te_nome_co_a5e468_idx'),
        ),
        migrations.AddIndex(
            model_name='tecnico',
            index=models.Index(fields=['cpf'], name='tecnicos_te_cpf_9de9d1_idx'),
        ),
    ]
