# Generated by Django 5.2.5 on 2025-11-05 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0006_cliente_qr_code_empreendimento_qr_code'),
        ('tecnicos', '0002_alter_tecnico_options_tecnico_bairro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tecnico',
            name='clientes',
            field=models.ManyToManyField(blank=True, related_name='tecnicos', to='cadastro.cliente', verbose_name='Clientes'),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='empreendimentos_vinculados',
            field=models.ManyToManyField(blank=True, related_name='tecnicos_vinculados', to='cadastro.empreendimento', verbose_name='Empreendimentos'),
        ),
    ]
